version: '3.9'
services:
  localstack: # LocalStack container
    image: localstack/localstack:3.2.0
    ports:
      # Map the port so you can access the API from the host machine
      - 4566:4566
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
    volumes:
      # Here you mount your setup file so it will be executed
      # when the container starts
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
